services:
  DB:
    container_name: mydb
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
     DB_ROOT_PASSWORD: root
     DB_DATABASE: todo
     DB_USER: user
     DB_PASSWORD: password
    volumes:
      - ./data:/var/lib/postgresql/data
  backend:
    container_name: mybackend
    build : ./backend
    depends_on:
      - DB
    ports:
      - 3345:8080
    environment:
      - API_PORT=8080
      - DB_HOST=mydb
  frontend:
    depends_on:
      - backend
    container_name: myfrontend
    build : ./frontend
    ports:
      - 3344:8000
    environment:
      - APP_PORT=8000
      - BACKEND_HOST=mybackend
      - BACKEND_PORT=8080

  