services:
  DB:
    container_name: mydb
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - fullstack
    volumes:
      - ./db-volume:/var/lib/postgresql/data
  backend:
    container_name: mybackend
    build : 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - DB
    environment:
      - API_PORT=8080
      - POSTGRES_HOST=mydb
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - fullstack
  frontend:
    depends_on:
      - backend
    container_name: myfrontend
    build :
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - fullstack
  nginx:
    container_name: mynginx
    depends_on:
      - backend
      - frontend
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - fullstack
networks:
  fullstack:
    driver: bridge
